// <auto-generated />
using System;
using JurayUniversal.Persistence.EF.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JurayUniversal.Persistence.EF.SQL.Migrations
{
    [DbContext(typeof(DashboardDbContext))]
    [Migration("20230713072520_changes-unknow")]
    partial class changesunknow
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JurayUniversal.Domain.Models.Blog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("BlogCategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Publish")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlogCategoryId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.BlogCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Publish")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BlogCategories");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ContactUs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactUs");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.EnableDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("DeviceInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisableDevice")
                        .HasColumnType("bit");

                    b.Property<string>("UserInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EnableDevices");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Show")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FAQs");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.GeneralFeature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GeneralFeatures");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.MailingSystem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationStatus")
                        .HasColumnType("int");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<string>("Receipient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Retries")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MailingSystems");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationStatus")
                        .HasColumnType("int");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Retries")
                        .HasColumnType("int");

                    b.Property<string>("SentVia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.NewsLetter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NewsLetter");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.PageCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("HomeSortFrom")
                        .HasColumnType("int");

                    b.Property<int>("MenuSortOrder")
                        .HasColumnType("int");

                    b.Property<bool>("Publish")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PageCategories");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.PageSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("ButtonLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disable")
                        .HasColumnType("bit");

                    b.Property<bool>("DisableButton")
                        .HasColumnType("bit");

                    b.Property<bool>("FixedAfterFooter")
                        .HasColumnType("bit");

                    b.Property<string>("FullDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HomePageSortOrder")
                        .HasColumnType("int");

                    b.Property<int>("HomeSortFrom")
                        .HasColumnType("int");

                    b.Property<string>("ImageKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiniTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageSortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Qoute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondImageKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowInHome")
                        .HasColumnType("bit");

                    b.Property<string>("TemplateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("WebPageId")
                        .HasColumnType("bigint");

                    b.Property<string>("YoutubeUrlLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("WebPageId");

                    b.ToTable("PageSections");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.PageSectionList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("ButtonLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disable")
                        .HasColumnType("bit");

                    b.Property<string>("IconText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiniTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoreDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PageSectionId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PageSectionId");

                    b.ToTable("PageSectionLists");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.PostModal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("ButtonLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModalOccurance")
                        .HasColumnType("int");

                    b.Property<int>("ModalTime")
                        .HasColumnType("int");

                    b.Property<bool>("Publish")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowDescription")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowImage")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowOnlyImage")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowTitle")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StopTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PostModal");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisableAmount")
                        .HasColumnType("bit");

                    b.Property<string>("FullDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiniTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProductCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowInDropdown")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowInHome")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowSamples")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StatusNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleBackgroundKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleBackgroundUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProductCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("HomeSortFrom")
                        .HasColumnType("int");

                    b.Property<int>("MenuSortOrder")
                        .HasColumnType("int");

                    b.Property<bool>("Publish")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProductFeature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFeatures");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProductSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSamples");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CVFilePathKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CVFilePathUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactRelationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ethnicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EyeColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteBooks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteFood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteMovies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteMusic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteSports")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteTravelDestinations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitHubProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HairColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Hobbies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Languages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedInProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PassportFilePathKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportFilePathUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserStatus")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectCategories");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectFeature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Challenges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DateFinised")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStarted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneralFeatureId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("GeneralFeatureId1")
                        .HasColumnType("bigint");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.Property<string>("ProjectMainId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProjectMainId1")
                        .HasColumnType("bigint");

                    b.Property<string>("Report")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GeneralFeatureId1");

                    b.HasIndex("ProjectMainId1");

                    b.ToTable("ProjectFeatures");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectMainId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProjectMainId1")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectMainId1");

                    b.ToTable("ProjectFiles");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectMain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Authentications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFinised")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStarted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastDateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogoKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Materials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileReferralId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectCatgeoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProjectCatgeoryId1")
                        .HasColumnType("bigint");

                    b.Property<int>("ProjectStatus")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Urls")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileReferralId");

                    b.HasIndex("ProjectCatgeoryId1");

                    b.ToTable("ProjectMains");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectPosition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectPositions");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Challenges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DateFinised")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStarted")
                        .HasColumnType("datetime2");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("ProjectFeatureId")
                        .HasColumnType("bigint");

                    b.Property<string>("Report")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProjectFeatureId");

                    b.ToTable("ProjectTasks");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectTeam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("DateLeft")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectMainId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProjectMainId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProjectMainId1");

                    b.ToTable("ProjectTeams");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLeft")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("ProjectPositionId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProjectTeamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProjectTeamId1")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProjectTeamId2")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProjectPositionId");

                    b.HasIndex("ProjectTeamId1");

                    b.HasIndex("ProjectTeamId2");

                    b.HasIndex("RoleId");

                    b.ToTable("ProjectUsers");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.Setting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ActivateProductsInHome")
                        .HasColumnType("bit");

                    b.Property<bool>("AddBlogToFooter")
                        .HasColumnType("bit");

                    b.Property<bool>("AddBlogToHome")
                        .HasColumnType("bit");

                    b.Property<bool>("AddBlogToMenu")
                        .HasColumnType("bit");

                    b.Property<bool>("AddFaqToFooter")
                        .HasColumnType("bit");

                    b.Property<bool>("AddFaqToHome")
                        .HasColumnType("bit");

                    b.Property<bool>("AddPartnerToHome")
                        .HasColumnType("bit");

                    b.Property<bool>("AddTestimonyToFooter")
                        .HasColumnType("bit");

                    b.Property<bool>("AddTestimonyToHome")
                        .HasColumnType("bit");

                    b.Property<string>("AddressOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressTwo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogDisplayTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DefaultAttendanceCloseTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DefaultAttendanceStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DefaultAttendanceStartTimeSaturday")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultTitleBackgroundKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultTitleBackgroundUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisableMainTopMenu")
                        .HasColumnType("bit");

                    b.Property<int>("EarlyMinute")
                        .HasColumnType("int");

                    b.Property<string>("EmailOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailThree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailTwo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookPage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleMap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramPage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobCardNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobCardTitleBackgroundKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobCardTitleBackgroundUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LateMinute")
                        .HasColumnType("int");

                    b.Property<int>("OntimeMinute")
                        .HasColumnType("int");

                    b.Property<string>("PhoneOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneThree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneTwo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qoute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReportCloseTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ShowEmailOneInFooter")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowEmailOneInTop")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowEmailThreeInFooter")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowEmailThreeInTop")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowEmailTwoInFooter")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowEmailTwoInTop")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowPhoneOneInFooter")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowPhoneOneInTop")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowPhoneThreeInFooter")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowPhoneThreeInTop")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowPhoneTwoInFooter")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowPhoneTwoInTop")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowProductsInFooter")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowProductsInMenu")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowSixProducts")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowThreeProducts")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowTwoProducts")
                        .HasColumnType("bit");

                    b.Property<string>("SignatureKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TiktokPage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterPage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VeryLateMinute")
                        .HasColumnType("int");

                    b.Property<string>("WorkingHour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YoutubeChannel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.Slider", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("ButtonLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVideo")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiniTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Show")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YoutubeVideo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.SuperSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("ActivateAccountsOnFinanceManagement")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateAttendance")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateBirthdayTools")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateBlogContent")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateBudgetOnFinanceManagement")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateChatCommnunicationTools")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateComingSoon")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateCommnunicationTools")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateCommunicationReportAndAnalysis")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateContactInformationContent")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateContactUsCommnunicationTools")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateContentManagement")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateContentReportAndAnalysis")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateDashboard")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateEmailTools")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateExpensesOnFinanceManagement")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateFaqContent")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateFinanceManagement")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateForumCommnunicationTools")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateJobReferrals")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateLogin")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateManagementTools")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateNewsletterTools")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateNoticeBoardCommnunicationTools")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateOnlyAuthorizedDevice")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateOrder")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivatePagesContent")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivatePaymentOnFinanceManagement")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateProductContent")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateProject")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateProjectReportAndAnalysis")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateProposalManagement")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateReport")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateReportAndAnalysis")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateReportOnFinanceManagement")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateRoles")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateSMS")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateSalaries")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateSettings")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateSiteMap")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateSliderContent")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateSmsTools")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateTask")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateTestimonyContent")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateTrainings")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateUser")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateUserManagement")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateUserReportAndAnalysis")
                        .HasColumnType("bit");

                    b.Property<bool>("ActivateVisitorsReportAndAnalysis")
                        .HasColumnType("bit");

                    b.Property<string>("BlogTemplateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ChartsDashboard")
                        .HasColumnType("bit");

                    b.Property<string>("ColorTemplateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CommunicationDashboard")
                        .HasColumnType("bit");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyIconKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyIconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyLogoKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyLogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyWebsiteLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyWhiteLogoKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyWhiteLogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Configuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DashboardCSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DashboardTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FinanceDashboard")
                        .HasColumnType("bit");

                    b.Property<string>("FooterTemplateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("JustWebsite")
                        .HasColumnType("bit");

                    b.Property<string>("LayoutCSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LiveConfiguration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginCSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginNoteFooter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginTemplateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OrderDashboard")
                        .HasColumnType("bit");

                    b.Property<string>("PageHeaderTemplateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductTemplateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductTitleHome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProjectsDashboard")
                        .HasColumnType("bit");

                    b.Property<bool>("RedirectTohttps")
                        .HasColumnType("bit");

                    b.Property<bool>("RedirectTohttpswww")
                        .HasColumnType("bit");

                    b.Property<string>("ReloaderTemplateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SMSTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowMadeByJuray")
                        .HasColumnType("bit");

                    b.Property<string>("SliderTemplateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatisticsDashboard")
                        .HasColumnType("bit");

                    b.Property<string>("TemplateLayoutKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UsersDashboard")
                        .HasColumnType("bit");

                    b.Property<string>("WebsiteTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SuperSettings");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.TemplateCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginLayout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateColorPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TemplateCategories");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.TemplateType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TemplateCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("TrackKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateCategoryId");

                    b.ToTable("TemplateTypes");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.Testimony", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Testimonies");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.WebPage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("DirectUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnableDirectUrl")
                        .HasColumnType("bit");

                    b.Property<int>("HomeSortFrom")
                        .HasColumnType("int");

                    b.Property<string>("ImageKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PageCategoryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Publish")
                        .HasColumnType("bit");

                    b.Property<bool>("SecurityPage")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowInFooter")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowInMainMenu")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowInMainTop")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowInMenuDropDown")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PageCategoryId");

                    b.ToTable("WebPages");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.Blog", b =>
                {
                    b.HasOne("JurayUniversal.Domain.Models.BlogCategory", "BlogCategory")
                        .WithMany("Blogs")
                        .HasForeignKey("BlogCategoryId");

                    b.Navigation("BlogCategory");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.PageSection", b =>
                {
                    b.HasOne("JurayUniversal.Domain.Models.WebPage", "WebPage")
                        .WithMany("PageSections")
                        .HasForeignKey("WebPageId");

                    b.Navigation("WebPage");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.PageSectionList", b =>
                {
                    b.HasOne("JurayUniversal.Domain.Models.PageSection", "PageSection")
                        .WithMany("PageSectionLists")
                        .HasForeignKey("PageSectionId");

                    b.Navigation("PageSection");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.Product", b =>
                {
                    b.HasOne("JurayUniversal.Domain.Models.ProductCategory", "ProductCategory")
                        .WithMany("Product")
                        .HasForeignKey("ProductCategoryId");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProductFeature", b =>
                {
                    b.HasOne("JurayUniversal.Domain.Models.Product", "Product")
                        .WithMany("ProductFeatures")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProductSample", b =>
                {
                    b.HasOne("JurayUniversal.Domain.Models.Product", "Product")
                        .WithMany("ProductSamples")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectFeature", b =>
                {
                    b.HasOne("JurayUniversal.Domain.Models.GeneralFeature", "GeneralFeature")
                        .WithMany()
                        .HasForeignKey("GeneralFeatureId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurayUniversal.Domain.Models.ProjectMain", "ProjectMain")
                        .WithMany("ProjectFeatures")
                        .HasForeignKey("ProjectMainId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralFeature");

                    b.Navigation("ProjectMain");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectFile", b =>
                {
                    b.HasOne("JurayUniversal.Domain.Models.ProjectMain", "ProjectMain")
                        .WithMany("ProjectFiles")
                        .HasForeignKey("ProjectMainId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectMain");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectMain", b =>
                {
                    b.HasOne("JurayUniversal.Domain.Models.Profile", "ProfileReferral")
                        .WithMany()
                        .HasForeignKey("ProfileReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurayUniversal.Domain.Models.ProjectCategory", "ProjectCatgeory")
                        .WithMany("ProjectMains")
                        .HasForeignKey("ProjectCatgeoryId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfileReferral");

                    b.Navigation("ProjectCatgeory");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectTask", b =>
                {
                    b.HasOne("JurayUniversal.Domain.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurayUniversal.Domain.Models.ProjectFeature", "ProjectFeature")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ProjectFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("ProjectFeature");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectTeam", b =>
                {
                    b.HasOne("JurayUniversal.Domain.Models.ProjectMain", "ProjectMain")
                        .WithMany()
                        .HasForeignKey("ProjectMainId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectMain");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectUser", b =>
                {
                    b.HasOne("JurayUniversal.Domain.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurayUniversal.Domain.Models.ProjectPosition", "ProjectPosition")
                        .WithMany()
                        .HasForeignKey("ProjectPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurayUniversal.Domain.Models.ProjectMain", "ProjectTeam")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectTeamId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurayUniversal.Domain.Models.ProjectTeam", null)
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectTeamId2");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Profile");

                    b.Navigation("ProjectPosition");

                    b.Navigation("ProjectTeam");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.TemplateType", b =>
                {
                    b.HasOne("JurayUniversal.Domain.Models.TemplateCategory", null)
                        .WithMany("TemplateTypes")
                        .HasForeignKey("TemplateCategoryId");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.WebPage", b =>
                {
                    b.HasOne("JurayUniversal.Domain.Models.PageCategory", "PageCategory")
                        .WithMany("WebPages")
                        .HasForeignKey("PageCategoryId");

                    b.Navigation("PageCategory");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("JurayUniversal.Domain.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("JurayUniversal.Domain.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurayUniversal.Domain.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("JurayUniversal.Domain.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.BlogCategory", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.PageCategory", b =>
                {
                    b.Navigation("WebPages");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.PageSection", b =>
                {
                    b.Navigation("PageSectionLists");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.Product", b =>
                {
                    b.Navigation("ProductFeatures");

                    b.Navigation("ProductSamples");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProductCategory", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectCategory", b =>
                {
                    b.Navigation("ProjectMains");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectFeature", b =>
                {
                    b.Navigation("ProjectTasks");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectMain", b =>
                {
                    b.Navigation("ProjectFeatures");

                    b.Navigation("ProjectFiles");

                    b.Navigation("ProjectUsers");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.ProjectTeam", b =>
                {
                    b.Navigation("ProjectUsers");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.TemplateCategory", b =>
                {
                    b.Navigation("TemplateTypes");
                });

            modelBuilder.Entity("JurayUniversal.Domain.Models.WebPage", b =>
                {
                    b.Navigation("PageSections");
                });
#pragma warning restore 612, 618
        }
    }
}
